name: WebAppYG
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - django=5.0.7
  - djangorestframework=3.15.2
  - django-cors-headers=4.3.1
  - django-extensions=3.2.3
  - celery=5.3.1
  - redis=4.6.0
  - django-celery-beat=2.5.0
  - django-celery-results=2.5.1
  - drf-spectacular=0.26.4
  - python-decouple=3.8
  - django-debug-toolbar=4.2.0
  - gunicorn=21.2.0
  - whitenoise=6.5.0
  - pandas=2.0.3
  - numpy=1.24.3
  - python-dateutil=2.8.2
  - pytz=2023.3
  - gdal
  - geos
  - proj
  - postgresql
  - psycopg2
  - pillow
  - pip
  - pip:
    - geopandas==0.13.2

